---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: testchatbotjul25
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testchatbotjul25 
  name: testchatbotjul25
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi